# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    workflow_dispatch:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_PATH: pact-exploration
  PROJECT_NAME: PactExploration
  PACT_BROKER_BASE_URL: https://stonepagamentos.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}
  GIT_COMMIT: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}
  GITHUB_ORG: "pactflow"
  PACTICIPANT: "pact-exploration"
  GITHUB_WEBHOOK_UUID: "04510dc1-7f0a-4ed2-997d-114bfa86f8ad"
  PACT_CLI: "docker run --rm -v ${PWD}:${PWD} -e $PACT_BROKER_BASE_URL -e $PACT_BROKER_TOKEN pactfoundation/pact-cli"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: $PROJECT_PATH

    - name: Build
      run: dotnet build --no-restore
      working-directory: $PROJECT_PATH/

  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          pact_provider: [
              # "pactflow-example-bi-directional-provider-dredd",
              # "pactflow-example-bi-directional-provider-restassured",
              # "pactflow-example-bi-directional-provider-postman",
              #'pactflow-example-provider'
              'PostmanApi'
          ]
    steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: $PROJECT_PATH/$PROJECT_NAME.Tests
  
  # Runs on branches as well, so we know the status of our PRs
  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Can I deploy?
        run: GIT_BRANCH=${GIT_REF:11} make can_i_deploy

  # Only deploy from master
  deploy:
    runs-on: ubuntu-latest
    needs: can-i-deploy
    steps:
      - uses: actions/checkout@v3
      - run: docker pull pactfoundation/pact-cli:latest .env echo"\n========== STAGE can-i-deploy? ==========\n" "${PACT_CLI}" broker can-i-deploy --pacticipant ${PACTICIPANT} --version ${GIT_COMMIT} --to-environment ${ENVIRONMENT} --retry-while-unknown 30 --retry-interval 10